name: Terraform Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Install tfcov
      run: |
        go install github.com/aquasecurity/tfcov@latest

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov checkov
        pip install -r requirements.txt

    - name: Run Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Run Terraform Init
      run: terraform init -backend=false

    - name: Run Terraform Validate
      run: terraform validate

    - name: Run Terraform Plan for Coverage
      run: |
        terraform plan -out=tfplan
        terraform show -json tfplan > plan.json
        tfcov -plan plan.json -coverage-report tf_coverage.json

    - name: Run Python Tests with Coverage
      run: |
        pytest tests/ --cov=. --cov-report=xml --cov-report=html

    - name: Run Checkov
      run: |
        checkov -d . --output-file-path checkov-report.json --output json
        checkov -d . --output-file-path checkov-report.md --output md

    - name: Create Combined Coverage Report
      run: |
        mkdir -p combined_coverage
        cp -r htmlcov/* combined_coverage/
        # Add Terraform coverage summary
        echo "## Terraform Coverage" > combined_coverage/terraform_coverage.md
        jq -r '.coverage[] | "* \(.file): \(.lines.covered)/\(.lines.total) lines covered"' tf_coverage.json >> combined_coverage/terraform_coverage.md

    - name: Upload Coverage Reports
      uses: actions/upload-artifact@v2
      with:
        name: coverage-reports
        path: |
          coverage.xml
          htmlcov/
          tf_coverage.json
          checkov-report.json
          checkov-report.md
          combined_coverage/

    - name: Coverage Summary
      run: |
        echo "Python Coverage Summary:"
        coverage report
        echo -e "\nTerraform Coverage Summary:"
        jq -r '.summary | "Total Coverage: \(.lines.coverage)%"' tf_coverage.json