name: Terraform Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.19'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Install tfcov
      run: |
        go install github.com/aquasecurity/tfcov@latest

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-terraform python-terraform
        pip install azure-identity azure-mgmt-resource azure-mgmt-storage

    - name: Run Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Run Terraform Init
      run: terraform init -backend=false

    - name: Run Terraform Validate
      run: terraform validate

    - name: Run Terraform Plan and TFCov
      run: |
        terraform plan -out=tfplan
        terraform show -json tfplan > plan.json
        tfcov -plan plan.json -coverage-report tf_coverage.json

    - name: Run Integration Tests with Python Coverage
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        pytest tests/ -v --cov=. --cov-report=xml --cov-report=html

    - name: Combine Coverage Reports
      run: |
        mkdir -p combined_coverage
        cp -r htmlcov/* combined_coverage/
        echo "## Terraform Coverage" > combined_coverage/terraform_coverage.md
        jq -r '.coverage[] | "* \(.file): \(.lines.covered)/\(.lines.total) lines covered"' tf_coverage.json >> combined_coverage/terraform_coverage.md

    - name: Upload Coverage Reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          combined_coverage/
          coverage.xml
          tf_coverage.json